import deepDiff from "deep-diff";
import { expect, test } from "vitest";
import { restoreDiffChanges } from "../src/functions/diff-utility";

test("restoreDeepDiffChanges", async () => {
    let data = {
        path: "/narration",
        storage: [
            {
                key: "___current_dialogue_memory___",
                value: {
                    text: "I just wanted to see what the new guy was like.",
                    character: "sly",
                    oltherParams: {},
                },
            },
            {
                key: "___last_dialogue_added_in_step_memory___",
                value: 14,
            },
            {
                key: "___flags___",
                value: [],
            },
            {
                key: "___opened_labels_counter___",
                value: {
                    start: {
                        biggestStep: 14,
                        openCount: 1,
                    },
                },
            },
            {
                key: "_input_value_",
                value: "Peter",
            },
            {
                key: "___last_input_added_in_step_memory___",
                value: 5,
            },
            {
                key: "___character___",
                value: {
                    mc: {
                        name: "Peter",
                    },
                },
            },
        ],
        canvas: {
            tickers: {
                "41a8f13900d641b94fc1d547c129f5f2f3d9766b_km9knm": {
                    id: "MoveTicker",
                    args: {
                        direction: "right",
                        speed: 300,
                        tickerAliasToResume: ["sly"],
                        aliasToRemoveAfter: [],
                        destination: {
                            x: 0.2,
                            y: 1,
                            type: "align",
                        },
                        startOnlyIfHaveTexture: true,
                    },
                    canvasElementAliases: ["sly"],
                },
                "170deb3d2b65d1d470ad0e59be142bcaf6933560_aiueh": {
                    id: "MoveTicker",
                    args: {
                        direction: "left",
                        speed: 300,
                        tickerAliasToResume: ["steph"],
                        aliasToRemoveAfter: [],
                        destination: {
                            x: 0.8,
                            y: 1,
                            type: "align",
                        },
                        startOnlyIfHaveTexture: true,
                    },
                    canvasElementAliases: ["steph"],
                },
            },
            tickersSteps: {},
            elements: {
                bg: {
                    pixivnId: "Image",
                    elements: [],
                    width: 1920,
                    height: 1080,
                    isRenderGroup: false,
                    blendMode: "inherit",
                    tint: 16777215,
                    alpha: 1,
                    angle: 0,
                    renderable: true,
                    rotation: 0,
                    scale: {
                        x: 1,
                        y: 1,
                    },
                    pivot: {
                        x: 0,
                        y: 0,
                    },
                    position: {
                        x: 0,
                        y: 0,
                    },
                    skew: {
                        x: 0,
                        y: 0,
                    },
                    visible: true,
                    x: 0,
                    y: 0,
                    eventMode: "passive",
                    interactive: false,
                    interactiveChildren: true,
                    hitArea: null,
                    textureData: {
                        url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fbg01-hallway.webp?alt=media",
                        alias: "bg01-hallway",
                    },
                    anchor: {
                        x: 0,
                        y: 0,
                    },
                    roundPixels: false,
                    onEvents: {},
                    loadIsStarted: false,
                },
                james: {
                    pixivnId: "ImageContainer",
                    elements: [
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 495,
                            height: 977,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-body.webp?alt=media",
                                alias: "m01-body",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 495,
                            height: 977,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-eyes-annoy.webp?alt=media",
                                alias: "m01-eyes-annoy",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 495,
                            height: 977,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-mouth-annoy00.webp?alt=media",
                                alias: "m01-mouth-annoy00",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                    ],
                    width: 495,
                    height: 977,
                    isRenderGroup: false,
                    blendMode: "inherit",
                    tint: 16777215,
                    alpha: 1,
                    angle: 0,
                    renderable: true,
                    rotation: 0,
                    scale: {
                        x: 1,
                        y: 1,
                    },
                    pivot: {
                        x: 0,
                        y: 0,
                    },
                    position: {
                        x: 712.5,
                        y: 103,
                    },
                    skew: {
                        x: 0,
                        y: 0,
                    },
                    visible: true,
                    x: 712.5,
                    y: 103,
                    eventMode: "passive",
                    interactive: false,
                    interactiveChildren: true,
                    hitArea: null,
                    align: {
                        x: 0.5,
                        y: 1,
                    },
                    loadIsStarted: false,
                },
                sly: {
                    pixivnId: "ImageContainer",
                    elements: [
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 546,
                            height: 980,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm01%2Ffm01-body.webp?alt=media",
                                alias: "fm01-body",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 546,
                            height: 980,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm01%2Ffm01-eyes-wow.webp?alt=media",
                                alias: "fm01-eyes-wow",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 546,
                            height: 980,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm01%2Ffm01-mouth-soft01.webp?alt=media",
                                alias: "fm01-mouth-soft01",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                    ],
                    width: 546,
                    height: 980,
                    isRenderGroup: false,
                    blendMode: "inherit",
                    tint: 16777215,
                    alpha: 1,
                    angle: 0,
                    renderable: true,
                    rotation: 0,
                    scale: {
                        x: 1,
                        y: 1,
                    },
                    pivot: {
                        x: 0,
                        y: 0,
                    },
                    position: {
                        x: -546,
                        y: 100,
                    },
                    skew: {
                        x: 0,
                        y: 0,
                    },
                    visible: true,
                    x: -546,
                    y: 100,
                    eventMode: "passive",
                    interactive: false,
                    interactiveChildren: true,
                    hitArea: null,
                    loadIsStarted: false,
                },
                steph: {
                    pixivnId: "ImageContainer",
                    elements: [
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 525,
                            height: 969,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm02%2Ffm02-body.webp?alt=media",
                                alias: "fm02-body",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 525,
                            height: 969,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm02%2Ffm02-eyes-nervous.webp?alt=media",
                                alias: "fm02-eyes-nervous",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 525,
                            height: 969,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm02%2Ffm02-mouth-nervous00.webp?alt=media",
                                alias: "fm02-mouth-nervous00",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                    ],
                    width: 525,
                    height: 969,
                    isRenderGroup: false,
                    blendMode: "inherit",
                    tint: 16777215,
                    alpha: 1,
                    angle: 0,
                    renderable: true,
                    rotation: 0,
                    scale: {
                        x: 1,
                        y: 1,
                    },
                    pivot: {
                        x: 0,
                        y: 0,
                    },
                    position: {
                        x: 2445,
                        y: 111,
                    },
                    skew: {
                        x: 0,
                        y: 0,
                    },
                    visible: true,
                    x: 2445,
                    y: 111,
                    eventMode: "passive",
                    interactive: false,
                    interactiveChildren: true,
                    hitArea: null,
                    loadIsStarted: false,
                },
            },
            stage: {
                pixivnId: "Container",
                elements: [],
                width: 3516,
                height: 1080,
                isRenderGroup: false,
                blendMode: "inherit",
                tint: 16777215,
                alpha: 1,
                angle: 0,
                renderable: true,
                rotation: 0,
                scale: {
                    x: 1,
                    y: 1,
                },
                pivot: {
                    x: 0,
                    y: 0,
                },
                position: {
                    x: 0,
                    y: 0,
                },
                skew: {
                    x: 0,
                    y: 0,
                },
                visible: true,
                x: 0,
                y: 0,
                eventMode: "passive",
                interactive: false,
                interactiveChildren: true,
                hitArea: null,
            },
            elementAliasesOrder: ["bg", "james", "sly", "steph"],
            tickersOnPause: {
                sly: {
                    tickerIdsExcluded: ["41a8f13900d641b94fc1d547c129f5f2f3d9766b_km9knm"],
                },
                steph: {
                    tickerIdsExcluded: ["170deb3d2b65d1d470ad0e59be142bcaf6933560_aiueh"],
                },
            },
            tickersToCompleteOnStepEnd: {
                tikersIds: [
                    {
                        id: "41a8f13900d641b94fc1d547c129f5f2f3d9766b_km9knm",
                    },
                    {
                        id: "170deb3d2b65d1d470ad0e59be142bcaf6933560_aiueh",
                    },
                ],
                stepAlias: [],
            },
        },
        sound: {
            soundsPlaying: {},
            soundAliasesOrder: [],
        },
        labelIndex: 14,
        openedLabels: [
            {
                label: "start",
                currentStepIndex: 14,
            },
        ],
    };
    let differences: deepDiff.Diff<any, any>[] = [
        {
            kind: "E",
            path: ["storage", 3, "value", "start", "biggestStep"],
            lhs: 13,
            rhs: 14,
        },
        {
            kind: "E",
            path: ["storage", 1, "value"],
            lhs: 13,
            rhs: 14,
        },
        {
            kind: "E",
            path: ["storage", 0, "value", "text"],
            lhs: "I know you're both watching, come on out already!",
            rhs: "I just wanted to see what the new guy was like.",
        },
        {
            kind: "E",
            path: ["storage", 0, "value", "character"],
            lhs: "james",
            rhs: "sly",
        },
        {
            kind: "N",
            path: ["canvas", "tickers", "41a8f13900d641b94fc1d547c129f5f2f3d9766b_km9knm"],
            rhs: {
                id: "MoveTicker",
                args: {
                    direction: "right",
                    speed: 300,
                    tickerAliasToResume: ["sly"],
                    aliasToRemoveAfter: [],
                    destination: {
                        x: 0.2,
                        y: 1,
                        type: "align",
                    },
                    startOnlyIfHaveTexture: true,
                },
                canvasElementAliases: ["sly"],
            },
        },
        {
            kind: "N",
            path: ["canvas", "tickers", "170deb3d2b65d1d470ad0e59be142bcaf6933560_aiueh"],
            rhs: {
                id: "MoveTicker",
                args: {
                    direction: "left",
                    speed: 300,
                    tickerAliasToResume: ["steph"],
                    aliasToRemoveAfter: [],
                    destination: {
                        x: 0.8,
                        y: 1,
                        type: "align",
                    },
                    startOnlyIfHaveTexture: true,
                },
                canvasElementAliases: ["steph"],
            },
        },
        {
            kind: "E",
            path: ["canvas", "elements", "james", "elements", 2, "textureData", "url"],
            lhs: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-mouth-annoy01.webp?alt=media",
            rhs: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-mouth-annoy00.webp?alt=media",
        },
        {
            kind: "E",
            path: ["canvas", "elements", "james", "elements", 2, "textureData", "alias"],
            lhs: "m01-mouth-annoy01",
            rhs: "m01-mouth-annoy00",
        },
        {
            kind: "N",
            path: ["canvas", "elements", "sly"],
            rhs: {
                pixivnId: "ImageContainer",
                elements: [
                    {
                        pixivnId: "Image",
                        elements: [],
                        width: 546,
                        height: 980,
                        isRenderGroup: false,
                        blendMode: "inherit",
                        tint: 16777215,
                        alpha: 1,
                        angle: 0,
                        renderable: true,
                        rotation: 0,
                        scale: {
                            x: 1,
                            y: 1,
                        },
                        pivot: {
                            x: 0,
                            y: 0,
                        },
                        position: {
                            x: 0,
                            y: 0,
                        },
                        skew: {
                            x: 0,
                            y: 0,
                        },
                        visible: true,
                        x: 0,
                        y: 0,
                        eventMode: "passive",
                        interactive: false,
                        interactiveChildren: true,
                        hitArea: null,
                        textureData: {
                            url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm01%2Ffm01-body.webp?alt=media",
                            alias: "fm01-body",
                        },
                        anchor: {
                            x: 0,
                            y: 0,
                        },
                        roundPixels: false,
                        onEvents: {},
                        loadIsStarted: false,
                    },
                    {
                        pixivnId: "Image",
                        elements: [],
                        width: 546,
                        height: 980,
                        isRenderGroup: false,
                        blendMode: "inherit",
                        tint: 16777215,
                        alpha: 1,
                        angle: 0,
                        renderable: true,
                        rotation: 0,
                        scale: {
                            x: 1,
                            y: 1,
                        },
                        pivot: {
                            x: 0,
                            y: 0,
                        },
                        position: {
                            x: 0,
                            y: 0,
                        },
                        skew: {
                            x: 0,
                            y: 0,
                        },
                        visible: true,
                        x: 0,
                        y: 0,
                        eventMode: "passive",
                        interactive: false,
                        interactiveChildren: true,
                        hitArea: null,
                        textureData: {
                            url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm01%2Ffm01-eyes-wow.webp?alt=media",
                            alias: "fm01-eyes-wow",
                        },
                        anchor: {
                            x: 0,
                            y: 0,
                        },
                        roundPixels: false,
                        onEvents: {},
                        loadIsStarted: false,
                    },
                    {
                        pixivnId: "Image",
                        elements: [],
                        width: 546,
                        height: 980,
                        isRenderGroup: false,
                        blendMode: "inherit",
                        tint: 16777215,
                        alpha: 1,
                        angle: 0,
                        renderable: true,
                        rotation: 0,
                        scale: {
                            x: 1,
                            y: 1,
                        },
                        pivot: {
                            x: 0,
                            y: 0,
                        },
                        position: {
                            x: 0,
                            y: 0,
                        },
                        skew: {
                            x: 0,
                            y: 0,
                        },
                        visible: true,
                        x: 0,
                        y: 0,
                        eventMode: "passive",
                        interactive: false,
                        interactiveChildren: true,
                        hitArea: null,
                        textureData: {
                            url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm01%2Ffm01-mouth-soft01.webp?alt=media",
                            alias: "fm01-mouth-soft01",
                        },
                        anchor: {
                            x: 0,
                            y: 0,
                        },
                        roundPixels: false,
                        onEvents: {},
                        loadIsStarted: false,
                    },
                ],
                width: 546,
                height: 980,
                isRenderGroup: false,
                blendMode: "inherit",
                tint: 16777215,
                alpha: 1,
                angle: 0,
                renderable: true,
                rotation: 0,
                scale: {
                    x: 1,
                    y: 1,
                },
                pivot: {
                    x: 0,
                    y: 0,
                },
                position: {
                    x: -546,
                    y: 100,
                },
                skew: {
                    x: 0,
                    y: 0,
                },
                visible: true,
                x: -546,
                y: 100,
                eventMode: "passive",
                interactive: false,
                interactiveChildren: true,
                hitArea: null,
                loadIsStarted: false,
            },
        },
        {
            kind: "N",
            path: ["canvas", "elements", "steph"],
            rhs: {
                pixivnId: "ImageContainer",
                elements: [
                    {
                        pixivnId: "Image",
                        elements: [],
                        width: 525,
                        height: 969,
                        isRenderGroup: false,
                        blendMode: "inherit",
                        tint: 16777215,
                        alpha: 1,
                        angle: 0,
                        renderable: true,
                        rotation: 0,
                        scale: {
                            x: 1,
                            y: 1,
                        },
                        pivot: {
                            x: 0,
                            y: 0,
                        },
                        position: {
                            x: 0,
                            y: 0,
                        },
                        skew: {
                            x: 0,
                            y: 0,
                        },
                        visible: true,
                        x: 0,
                        y: 0,
                        eventMode: "passive",
                        interactive: false,
                        interactiveChildren: true,
                        hitArea: null,
                        textureData: {
                            url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm02%2Ffm02-body.webp?alt=media",
                            alias: "fm02-body",
                        },
                        anchor: {
                            x: 0,
                            y: 0,
                        },
                        roundPixels: false,
                        onEvents: {},
                        loadIsStarted: false,
                    },
                    {
                        pixivnId: "Image",
                        elements: [],
                        width: 525,
                        height: 969,
                        isRenderGroup: false,
                        blendMode: "inherit",
                        tint: 16777215,
                        alpha: 1,
                        angle: 0,
                        renderable: true,
                        rotation: 0,
                        scale: {
                            x: 1,
                            y: 1,
                        },
                        pivot: {
                            x: 0,
                            y: 0,
                        },
                        position: {
                            x: 0,
                            y: 0,
                        },
                        skew: {
                            x: 0,
                            y: 0,
                        },
                        visible: true,
                        x: 0,
                        y: 0,
                        eventMode: "passive",
                        interactive: false,
                        interactiveChildren: true,
                        hitArea: null,
                        textureData: {
                            url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm02%2Ffm02-eyes-nervous.webp?alt=media",
                            alias: "fm02-eyes-nervous",
                        },
                        anchor: {
                            x: 0,
                            y: 0,
                        },
                        roundPixels: false,
                        onEvents: {},
                        loadIsStarted: false,
                    },
                    {
                        pixivnId: "Image",
                        elements: [],
                        width: 525,
                        height: 969,
                        isRenderGroup: false,
                        blendMode: "inherit",
                        tint: 16777215,
                        alpha: 1,
                        angle: 0,
                        renderable: true,
                        rotation: 0,
                        scale: {
                            x: 1,
                            y: 1,
                        },
                        pivot: {
                            x: 0,
                            y: 0,
                        },
                        position: {
                            x: 0,
                            y: 0,
                        },
                        skew: {
                            x: 0,
                            y: 0,
                        },
                        visible: true,
                        x: 0,
                        y: 0,
                        eventMode: "passive",
                        interactive: false,
                        interactiveChildren: true,
                        hitArea: null,
                        textureData: {
                            url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Ffm02%2Ffm02-mouth-nervous00.webp?alt=media",
                            alias: "fm02-mouth-nervous00",
                        },
                        anchor: {
                            x: 0,
                            y: 0,
                        },
                        roundPixels: false,
                        onEvents: {},
                        loadIsStarted: false,
                    },
                ],
                width: 525,
                height: 969,
                isRenderGroup: false,
                blendMode: "inherit",
                tint: 16777215,
                alpha: 1,
                angle: 0,
                renderable: true,
                rotation: 0,
                scale: {
                    x: 1,
                    y: 1,
                },
                pivot: {
                    x: 0,
                    y: 0,
                },
                position: {
                    x: 2445,
                    y: 111,
                },
                skew: {
                    x: 0,
                    y: 0,
                },
                visible: true,
                x: 2445,
                y: 111,
                eventMode: "passive",
                interactive: false,
                interactiveChildren: true,
                hitArea: null,
                loadIsStarted: false,
            },
        },
        {
            kind: "E",
            path: ["canvas", "stage", "width"],
            lhs: 1920,
            rhs: 3516,
        },
        {
            kind: "A",
            path: ["canvas", "elementAliasesOrder"],
            index: 3,
            item: {
                kind: "N",
                rhs: "steph",
            },
        },
        {
            kind: "A",
            path: ["canvas", "elementAliasesOrder"],
            index: 2,
            item: {
                kind: "N",
                rhs: "sly",
            },
        },
        {
            kind: "N",
            path: ["canvas", "tickersOnPause", "sly"],
            rhs: {
                tickerIdsExcluded: ["41a8f13900d641b94fc1d547c129f5f2f3d9766b_km9knm"],
            },
        },
        {
            kind: "N",
            path: ["canvas", "tickersOnPause", "steph"],
            rhs: {
                tickerIdsExcluded: ["170deb3d2b65d1d470ad0e59be142bcaf6933560_aiueh"],
            },
        },
        {
            kind: "A",
            path: ["canvas", "tickersToCompleteOnStepEnd", "tikersIds"],
            index: 1,
            item: {
                kind: "N",
                rhs: {
                    id: "170deb3d2b65d1d470ad0e59be142bcaf6933560_aiueh",
                },
            },
        },
        {
            kind: "A",
            path: ["canvas", "tickersToCompleteOnStepEnd", "tikersIds"],
            index: 0,
            item: {
                kind: "N",
                rhs: {
                    id: "41a8f13900d641b94fc1d547c129f5f2f3d9766b_km9knm",
                },
            },
        },
        {
            kind: "N",
            path: ["sound", "filters"],
            rhs: undefined,
        },
        {
            kind: "E",
            path: ["labelIndex"],
            lhs: 13,
            rhs: 14,
        },
        {
            kind: "E",
            path: ["openedLabels", 0, "currentStepIndex"],
            lhs: 13,
            rhs: 14,
        },
    ];
    let res = restoreDiffChanges(data, differences);

    expect(res).toEqual({
        path: "/narration",
        storage: [
            {
                key: "___current_dialogue_memory___",
                value: {
                    text: "I know you're both watching, come on out already!",
                    character: "james",
                    oltherParams: {},
                },
            },
            {
                key: "___last_dialogue_added_in_step_memory___",
                value: 13,
            },
            {
                key: "___flags___",
                value: [],
            },
            {
                key: "___opened_labels_counter___",
                value: {
                    start: {
                        biggestStep: 13,
                        openCount: 1,
                    },
                },
            },
            {
                key: "_input_value_",
                value: "Peter",
            },
            {
                key: "___last_input_added_in_step_memory___",
                value: 5,
            },
            {
                key: "___character___",
                value: {
                    mc: {
                        name: "Peter",
                    },
                },
            },
        ],
        canvas: {
            tickers: {},
            tickersSteps: {},
            elements: {
                bg: {
                    pixivnId: "Image",
                    elements: [],
                    width: 1920,
                    height: 1080,
                    isRenderGroup: false,
                    blendMode: "inherit",
                    tint: 16777215,
                    alpha: 1,
                    angle: 0,
                    renderable: true,
                    rotation: 0,
                    scale: {
                        x: 1,
                        y: 1,
                    },
                    pivot: {
                        x: 0,
                        y: 0,
                    },
                    position: {
                        x: 0,
                        y: 0,
                    },
                    skew: {
                        x: 0,
                        y: 0,
                    },
                    visible: true,
                    x: 0,
                    y: 0,
                    eventMode: "passive",
                    interactive: false,
                    interactiveChildren: true,
                    hitArea: null,
                    textureData: {
                        url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fbg01-hallway.webp?alt=media",
                        alias: "bg01-hallway",
                    },
                    anchor: {
                        x: 0,
                        y: 0,
                    },
                    roundPixels: false,
                    onEvents: {},
                    loadIsStarted: false,
                },
                james: {
                    pixivnId: "ImageContainer",
                    elements: [
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 495,
                            height: 977,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-body.webp?alt=media",
                                alias: "m01-body",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 495,
                            height: 977,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-eyes-annoy.webp?alt=media",
                                alias: "m01-eyes-annoy",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                        {
                            pixivnId: "Image",
                            elements: [],
                            width: 495,
                            height: 977,
                            isRenderGroup: false,
                            blendMode: "inherit",
                            tint: 16777215,
                            alpha: 1,
                            angle: 0,
                            renderable: true,
                            rotation: 0,
                            scale: {
                                x: 1,
                                y: 1,
                            },
                            pivot: {
                                x: 0,
                                y: 0,
                            },
                            position: {
                                x: 0,
                                y: 0,
                            },
                            skew: {
                                x: 0,
                                y: 0,
                            },
                            visible: true,
                            x: 0,
                            y: 0,
                            eventMode: "passive",
                            interactive: false,
                            interactiveChildren: true,
                            hitArea: null,
                            textureData: {
                                url: "https://firebasestorage.googleapis.com/v0/b/pixi-vn.appspot.com/o/public%2Fbreakdown%2Fm01%2Fm01-mouth-annoy01.webp?alt=media",
                                alias: "m01-mouth-annoy01",
                            },
                            anchor: {
                                x: 0,
                                y: 0,
                            },
                            roundPixels: false,
                            onEvents: {},
                            loadIsStarted: false,
                        },
                    ],
                    width: 495,
                    height: 977,
                    isRenderGroup: false,
                    blendMode: "inherit",
                    tint: 16777215,
                    alpha: 1,
                    angle: 0,
                    renderable: true,
                    rotation: 0,
                    scale: {
                        x: 1,
                        y: 1,
                    },
                    pivot: {
                        x: 0,
                        y: 0,
                    },
                    position: {
                        x: 712.5,
                        y: 103,
                    },
                    skew: {
                        x: 0,
                        y: 0,
                    },
                    visible: true,
                    x: 712.5,
                    y: 103,
                    eventMode: "passive",
                    interactive: false,
                    interactiveChildren: true,
                    hitArea: null,
                    align: {
                        x: 0.5,
                        y: 1,
                    },
                    loadIsStarted: false,
                },
            },
            stage: {
                pixivnId: "Container",
                elements: [],
                width: 1920,
                height: 1080,
                isRenderGroup: false,
                blendMode: "inherit",
                tint: 16777215,
                alpha: 1,
                angle: 0,
                renderable: true,
                rotation: 0,
                scale: {
                    x: 1,
                    y: 1,
                },
                pivot: {
                    x: 0,
                    y: 0,
                },
                position: {
                    x: 0,
                    y: 0,
                },
                skew: {
                    x: 0,
                    y: 0,
                },
                visible: true,
                x: 0,
                y: 0,
                eventMode: "passive",
                interactive: false,
                interactiveChildren: true,
                hitArea: null,
            },
            elementAliasesOrder: ["bg", "james"],
            tickersOnPause: {},
            tickersToCompleteOnStepEnd: {
                tikersIds: [],
                stepAlias: [],
            },
        },
        sound: {
            soundsPlaying: {},
            soundAliasesOrder: [],
        },
        labelIndex: 13,
        openedLabels: [
            {
                label: "start",
                currentStepIndex: 13,
            },
        ],
    });
});
