export const juliette = "___pixivn_juliette___"
export const eggHeadImage = "https://pixijs.com/assets/eggHead.png"
export const eggHeadName = `<span style="color:purple">Egg Head</span>`
export const flowerTopImage = "https://pixijs.com/assets/flowerTop.png"
export const flowerTopName = `<span style="color:green">Flower Top</span>`
export const helmlokImage = "https://pixijs.com/assets/helmlok.png"
export const helmlokName = `<span style="color:blue">Helmlok</span>`
export const skullyImage = "https://pixijs.com/assets/skully.png"
export const skullyName = `<span style="color:red">Skully</span>`
export const bunnyImage = "https://pixijs.com/assets/bunny.png"
export const bunnyName = `Bunny`
export const videoLink = "https://pixijs.com/assets/video.mp4"
export const birdAudio = "https://pixijs.io/sound/examples/resources/bird.mp3"
export const musicalAudio = "https://pixijs.io/sound/examples/resources/musical.mp3"
export const TEST_LABEL = "___pixi_vn_example_start_label___"
export const OPEN_LINK_LABEL = "___pixi_vn_open_link___"
export const RESTART_TEST_LABEL = "___pixi_vn_restart_test_label___"
export const BASE_CANVAS_ELEMENT_LABEL = "___pixi_vn_base_canvas_element_label___"
// export const CANVAS_EVENTS_TEST_LABEL = "___pixi_vn_canvas_events_test___"
export const CUSTOM_TICKER_CANVAS_ELEMENT_TEST_LABEL = "___pixi_vn_custom_ticker_canvas_element_test___"
export const IMAGE_ANIMAIONS_TEST_LABEL = "___pixi_vn_images_animations_test___"
export const INPUT_TEST_LABEL = "___pixi_vn_input_test___"
export const MARKDOWN_TEST_LABEL = "___pixi_vn_markdown_test___"
export const SOUND_TEST_LABEL = "___pixi_vn_sound_test___"
export const STEP_LABEL_TEST_LABEL = "___pixi_vn_step_label_test___"
export const VIDEO_TEST_LABEL = "___pixi_vn_video_test___"
export const IMAGE_DISSOLVE_TEST_LABEL = "___pixi_vn_images_dissolve_test___"
export const IMAGE_FADE_TEST_LABEL = "___pixi_vn_images_fade_test___"
export const IMAGE_ROTATE_TEST_LABEL = "___pixi_vn_images_rotate_test___"
export const IMAGE_MOVE_TEST_LABEL = "___pixi_vn_images_move_test___"
export const IMAGE_ZOOM_TEST_LABEL = "___pixi_vn_images_zoom_test___"
export const IMAGE_MOVE_IN_OUT_TEST_LABEL = "___pixi_vn_images_move_in_out_test___"
export const IMAGE_ZOOM_IN_OUT_TEST_LABEL = "___pixi_vn_images_zoom_in_out_test___"
export const IMAGE_PUSH_IN_OUT_TEST_LABEL = "___pixi_vn_images_push_in_out_test___"
export const IMAGES_ADD_SAME_TAG_TEST_LABEL = "___pixi_vn_images_add_same_tag_test___"
export const IMAGES_SHAKE_STAGE_TEST_LABEL = "___pixi_vn_images_shake_stage_test___"
export const IMAGE_CONTAINER_TEST_LABEL = "___pixi_vn_image_container_test___"
export const IMAGES_CUSTOM_POSITION_TEST_LABEL = "___pixi_vn_images_custom_position_test___"
